### PR TITLE
add support for m & z values in the destination

### LINKED ISSUE #223: Add support for m & z values
### Steps to reproduce
1. Create a pallet that points to a source feature class that has m- or z-values enabled. `SGID10.TRANSPORTATION.UDOTRoutes_LRS` is an example of m-values. The [roadkill pallet](https://github.com/agrc/roadkill-mobile/blob/47e8b34513f80cc042469c0b9be73a8c25642e6f/scripts/roadkill_pallet.py#L74) uses this layer.
1. `forklift lift`

### Expected behavior
The destination feature class should have the m- and/or z-values preserved.

### Actual behavior
The m- and z-values are gone. For example, here is `SGID10.TRANSPORTATION.UDOTRoutes_LRS`:
image

and here is `C:\MapData\transportation.gdb\UDOTRoutes_LRS`
image

### Research
We use `arcpy.management.CreateFeatureclass(..)` when we create the destination feature class: https://github.com/agrc/forklift/blob/2612d97c765c6fbbfee621fb8d7e3750b4443381/src/forklift/core.py#L254
[The docs](http://pro.arcgis.com/en/pro-app/tool-reference/data-management/create-feature-class.htm#GUID-E27A76C6-9B96-4134-A2D4-96CF8BE86F22) show `has_m` and `has_z` parameters in addition to supporting `arcpy.env.outputMFlag`. I would have guessed that the default would be to keep whatever the template feature class has but maybe not. I think that setting `has_m` and `haz_z` to `SAME_AS_TEMPLATE` should solve the problem. I'll test it and see.

### PR DESCRIPTION
**Pull request by stdavis**
Closes #223

## Description of Changes
Adds support for m & z values.

### Test results and coverage
image

### Speed test results
image

### CODE REVIEW

**Comment by stdavis** [comment]
Not sure that forklift is actually copying m-values...I'll figure it out...

**Comment by steveoh** [comment]
So the template thing did not work properly?

**Comment by stdavis** [comment]
The code for this PR works as expected. The destination feature class has m-values enabled. However, more work needs to be done on the code that actually copies the data...
image

**Comment by steveoh** [comment]
bummer...

**Comment by stdavis** [comment]
I forgot about the changes temp feature class.

**Pull request merged**
