### PR TITLE
add a sample batch file

### PR DESCRIPTION
**Pull request by stdavis**
This will help people schedule forklift to run via Windows Scheduler.

### CODE REVIEW

**Comment by stdavis** [comment]
Sounds good to me. Can we do that now? How?

**Comment by steveoh** [comment]
To do that @stdavis I think you can 

`conda create -n forklift --clone=arcgispro-py3`

I'm not sure if we would need `proswap` unless there are calls made via `propy` which I do not think we have.

**Comment by stdavis** [comment]
I finally got around to doing this on the server since I had to wipe the slate clean to downgrade. We now have a `forklift-env` virtual environment on .58. I added the "-env" because I thought it would get confusing to have the virtual environment the same name as the executable.

**Comment by stdavis** [comment]
I also added some docs to the readme.

**Comment by stdavis** [comment]
This caused problems with forklift being able to write to the garage folder. Hold off on this until we get it worked out.

**Comment by stdavis** [comment]
I couldn't get the new conda environment to work and have since switched back to `arcgispro-py3`. Can we merge this PR for now? Then if we ever get the new conda environment working we can update at that point?

**Comment by steveoh** [comment]
👌

**Pull request merged**
