### PR TITLE
Hash Field

### PR DESCRIPTION
**Pull request by stdavis**
## Description of Changes
This pull request adds a new field to the destination data for the hashes thus eliminating the need for the hash gdb.

- [x] Still need to strip the new field after copying to production.

This isn't going to work for the crates that have their destination pointed at SDE. But maybe that's should be done within the pallet and not in a crate?

### Test results and coverage
```
.............................................................................
.............................................................................
Name                     Stmts   Miss     Cover   Missing
---------------------------------------------------------
forklift\arcgis.py          65      3    95.38%   48, 96-98
forklift\cli.py            245     61    75.10%   111-112, 148, 183-188, 195, 242-245, 293-310, 317-328, 338-382
forklift\core.py           182      6    96.70%   99, 123, 152, 160-161, 338
forklift\lift.py           160     26    83.75%   44-45, 163-183, 193-195, 207-209, 224, 232-234, 268, 283
forklift\models.py         165      4    97.58%   85, 318, 353-354
---------------------------------------------------------
TOTAL                      908    100    88.99%

5 files skipped due to complete coverage.
-----------------------------------------------------------------------------
154 tests run in 378.707 seconds (154 tests passed)
___________________________________ summary ___________________________________
  unit: commands succeeded
  congratulations :)

  lint: commands succeeded
  congratulations :)
```

### Speed test results
```
Speed Test Results
Dry Run: 3.99 minutes
Repeat: 79.39 seconds
```

### CODE REVIEW

**Comment by stdavis** [comment]
Or maybe for crates that need to update SDE data they should use `staging_rack` for destination but not `copy_data` and then manually truncate and append into SDE in `process`?

**Comment by stdavis** [comment]
OK. This is ready for reviews when you guys get some time.

**Comment by stdavis** [comment]
:+1::+1::+1:
image

**Comment by keatonwalker** [comment]
This is looking good to me. I'm excited to see how it works over a few nights.

**Comment by stdavis** [comment]
@steveoh & @keatonwalker: You guys good with this?

**Pull request merged**
