### PR TITLE
Add optional argument parameter when running a specific pallet

### PR DESCRIPTION
**Pull request by stdavis**
Supercedes #59

### CODE REVIEW

**Comment by steveoh** [comment]
LGTM

**Comment by stdavis** [comment]
Merged

**Comment by steveoh** [comment]
This will only work when running a specific pallet correct? Otherwise the value will be None when run from `forklift lift`.

**Comment by stdavis** [comment]
Yes. It will only work when pointing at a specific file. If there is more than one pallet defined in the file then all get the parameter. The use case is when I need to update a specific layer for DEQ.

**Comment by steveoh** [comment]
Yes I was thinking about crash and being able to run the pallet in dev/stage/prod mode. I decided to have the ability to pass it in as an optional param if running the pallet but default to prod otherwise.

**Pull request closed without merging**
