### PR TITLE
better clean up of arcpy.env variables

### PR DESCRIPTION
**Pull request by stdavis**
I have a feeling that this will solve the OGM issue but haven't tested. I added a manually reset in that pallet just to be safe.

Either way this needed to be cleaned up.

### CODE REVIEW

**Comment by steveoh** [comment]
Why is the reset happening in has_changes?

**Comment by stdavis** [comment]
Because that's where it's set. Everywhere else in forklift that uses those env vars was already cleaning up after itself.

**Comment by stdavis** [comment]
has_changes does reprojecting so that the comparisons are correct.

**Comment by steveoh** [comment]
:shipit:

**Pull request merged**
